export const TEST_IDS = {
  shell: {
    layout: 'shell-layout',
    sidebar: 'shell-sidebar',
    sidebarCourseLink: 'shell-sidebar-course-link',
    authMenuTrigger: 'shell-auth-menu-trigger',
  },
  dashboard: {
    page: 'dashboard-page',
    courseList: 'dashboard-course-list',
    courseListEmpty: 'dashboard-course-list-empty',
    addCourseButton: 'dashboard-add-course-button',
    courseCard: 'dashboard-course-card',
  },
  addCourse: {
    page: 'add-course-page',
    form: 'add-course-form',
    courseCodeInput: 'add-course-course-code-input',
    termTrigger: 'add-course-term-trigger',
    schoolTrigger: 'add-course-school-trigger',
    firstDayTrigger: 'add-course-first-day-trigger',
    firstDayCalendar: 'add-course-first-day-calendar',
    daypartTrigger: 'add-course-daypart-trigger',
    additionalInfoToggle: 'add-course-additional-info-toggle',
    userContextInput: 'add-course-user-context-input',
    submitButton: 'add-course-submit-button',
    retryButton: 'add-course-retry-button',
    goToCourseButton: 'add-course-go-to-course-button',
    successAlert: 'add-course-success-alert',
  },
  coursePage: {
    page: 'course-page',
    actionsTrigger: 'course-page-actions-trigger',
    searchInput: 'course-page-search-input',
    hideCompletedToggle: 'course-page-hide-completed-toggle',
    addTaskButton: 'course-page-add-task-button',
    taskList: 'course-page-task-list',
    emptyState: 'course-page-empty-state',
  },
  addTaskDialog: {
    dialog: 'add-task-dialog',
    courseSelect: 'add-task-course-select',
    titleInput: 'add-task-title-input',
    notesInput: 'add-task-notes-input',
    typeSelect: 'add-task-type-select',
    dueDateTrigger: 'add-task-due-date-trigger',
    dueDateCalendar: 'add-task-due-date-calendar',
    estimatedEffortInput: 'add-task-estimated-effort-input',
    submitButton: 'add-task-submit-button',
    cancelButton: 'add-task-cancel-button',
    createMoreCheckbox: 'add-task-create-more-checkbox',
  },
  task: {
    card: 'task-card',
    actionsTrigger: 'task-actions-trigger',
    statusTrigger: 'task-status-trigger',
    nextStatusButton: 'task-next-status-button',
    dueDateTrigger: 'task-due-date-trigger',
    dueDateCalendar: 'task-due-date-calendar',
  },
} as const;
